Upgrade CI (23 Aug 2023 08:32:49)

diff --git a/.github/workflows/operator_release_manual.yaml b/.github/workflows/operator_release_manual.yaml
--- a/.github/workflows/operator_release_manual.yaml
+++ b/.github/workflows/operator_release_manual.yaml
@@ -19,9 +19,9 @@ on:
 
 
       index:
-        description: 'Target index (e.g. v4.10, v4.10-db)'
+        description: 'Target index (as a JSON list, e.g. ["v4.10-db", "v4.11"])'
         required: true
-        default: 'v4.10-db'
+        default: '["v4.6-db", "v4.7-db", "v4.8-db", "v4.9-db", "v4.10-db", "v4.11-rc"]'
 
       list_of_operators:
         description: 'List of operators to be synced in the index, list has to be devided by spaces (e.g. aqua ripsaw)'
@@ -64,6 +64,8 @@ env:
   OPP_THIS_REPO_BASE: "https://github.com"
   OPP_THIS_REPO: "redhat-openshift-ecosystem/okd-operators"
   OPP_THIS_BRANCH: "main"
+  INDEX_PATH_TO_SIGN: "not-defined"
+  SIGNATURE_ENDPOINT: "https://not-defined"
   OPP_REVIEWERS_ENABLED: 0
 
 
@@ -77,27 +79,21 @@ env:
   QUAY_APPREG_TOKEN: ${{ secrets.QUAY_APPREG_TOKEN }}
   QUAY_COURIER_TOKEN: ${{ secrets.QUAY_COURIER_TOKEN }}
   REPO_GHA_PAT: ${{ secrets.REPO_GHA_PAT }}
+  IIB_INPUT_REGISTRY_TOKEN: ${{ secrets.IIB_INPUT_REGISTRY_TOKEN }}
 
 jobs:
   pr-check:
     name: "PR-traffic-light"
     runs-on: ubuntu-latest
     steps:
-      - name: Block until there is no running workflow
-        uses: softprops/turnstyle@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
       - id: files
-        uses: jitterbit/get-changed-files@v1
+        uses: masesgroup/retrieve-changed-files@v2
         continue-on-error: true
-      - id: prinfo
-        uses: actions-ecosystem/action-get-merged-pull-request@v1
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+
       - name: Set up Python
-        uses: actions/setup-python@v2
+        uses: actions/setup-python@v4
         with:
           python-version: '3.x'
       - name: Install dependencies
@@ -109,16 +105,37 @@ jobs:
           OPP_MODIFIED_FILES: "${{ steps.files.outputs.modified }}"
           OPP_RENAMED_FILES: "${{ steps.files.outputs.renamed }}"
           OPP_REMOVED_FILES: "${{ steps.files.outputs.removed }}"
-          OPP_LABELS: "${{ steps.prinfo.outputs.labels }}"
+
         run: |
-          echo "PR : ${{ steps.prinfo.outputs.number }}"
-          echo "labels : ${{ steps.prinfo.outputs.labels }}"
+          if [ -z "${{ github.event.inputs.list_of_operators }}" ]
+          then
+                echo "Found an empty input - list_of_operators     [OK]"
+          else
+                OPP_MODIFIED_FILES=""
+                for operator_to_loop in ${{ github.event.inputs.list_of_operators }}; do
+                  echo "Processing $operator_to_loop"
+                  if [ -z "$OPP_MODIFIED_FILES" ]
+                  then 
+                    echo "...inicializing OPP_MODIFIED_FILES"
+                    OPP_MODIFIED_FILES="$(find operators/$operator_to_loop/ -type f -name "*.clusterserviceversion.yaml" | tail -n 1)"
+                  else
+                    echo "...extending OPP_MODIFIED_FILES"
+                    OPP_MODIFIED_FILES="$OPP_MODIFIED_FILES $(find operators/$operator_to_loop/ -type f -name "*.clusterserviceversion.yaml" | tail -n 1)"
+                  fi
+                done
+          fi
+          echo "OPP_MODIFIED_FILES=$OPP_MODIFIED_FILES"
+
           echo "OPP_LABELS=$OPP_LABELS"
           echo "Using script '$OPP_SCRIPT_ENV_URL' ..."
           bash <(curl -sL $OPP_SCRIPT_ENV_URL)
-
+      - name: Block until there is no running workflow
+        if: steps.op-traffic-light.outputs.opp_release_ready == '1'
+        uses: softprops/turnstyle@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     outputs:
-      opp_labels: "${{ steps.prinfo.outputs.labels }}"
+
       opp_test_ready: "${{ steps.op-traffic-light.outputs.opp_test_ready }}"
       opp_release_ready: "${{ steps.op-traffic-light.outputs.opp_release_ready }}"
       opp_stream: "${{ steps.op-traffic-light.outputs.opp_stream }}"
@@ -127,6 +144,8 @@ jobs:
       opp_ci_yaml_only: "${{ steps.op-traffic-light.outputs.opp_ci_yaml_only }}"
       opp_ver_overwrite: "${{ steps.op-traffic-light.outputs.opp_ver_overwrite }}"
       opp_op_delete: "${{ steps.op-traffic-light.outputs.opp_op_delete }}"
+      opp_recreate: "${{ steps.op-traffic-light.outputs.opp_recreate }}"
+      opp_is_new_operatror: "${{ steps.op-traffic-light.outputs.opp_is_new_operatror }}"
       opp_release_delete_appreg: "${{ steps.op-traffic-light.outputs.opp_release_delete_appreg }}"
       opp_pr_title: "${{ steps.op-traffic-light.outputs.opp_pr_title }}"
       opp_auto_packagemanifest_cluster_version_label: "${{ steps.op-traffic-light.outputs.opp_auto_packagemanifest_cluster_version_label }}"
@@ -139,7 +158,7 @@ jobs:
     strategy:
       matrix:
 
-        index-tag: ['${{ github.event.inputs.index }}']
+        index-tag: ${{ fromJson(github.event.inputs.index) }}
 
       fail-fast: false
     steps:
@@ -171,7 +190,6 @@ jobs:
           echo "OPP_LABELS=$OPP_LABELS"
           FAKE_RC=false
           FAKE_TYPE=$(echo $OPERATOR_INDEX_TAG | cut -d '-' -f 2)
-          [[ $FAKE_TYPE == *rc* ]] && FAKE_RC=true || true
 
           echo "op_delete_${OPERATOR_INDEX_TAG} operators/${{ needs.pr-check.outputs.opp_name }}/${{ needs.pr-check.outputs.opp_version }} $OPP_THIS_REPO $OPP_THIS_BRANCH"
           bash <(curl -sL $OPP_SCRIPT_URL) op_delete_${OPERATOR_INDEX_TAG} operators/${{ needs.pr-check.outputs.opp_name }}/${{ needs.pr-check.outputs.opp_version }} $OPP_THIS_REPO $OPP_THIS_BRANCH || $FAKE_RC
@@ -180,7 +198,7 @@ jobs:
     name: "Index check / ocp"
     needs: [pr-check, remove-ocp ]
 
-    if: needs.pr-check.outputs.opp_release_ready == '1'
+    if: needs.pr-check.outputs.opp_release_ready == '1' && (needs.pr-check.outputs.opp_op_delete == '0' || needs.pr-check.outputs.opp_is_new_operatror == '1' || needs.pr-check.outputs.opp_recreate == '1' )
     runs-on: ubuntu-latest
     steps:
       - name: List of missing operators
@@ -195,11 +213,13 @@ jobs:
           OPP_INDEX_CHECK_ONLY: 1
         run: |
  
-          TARGET_INDEX_RAW=${{ github.event.inputs.index }}
-          TARGET_INDEX_RAW=$(echo $TARGET_INDEX_RAW|cut -d '-' -f1)
-          TARGET_INDEX_UNDERLINE=$(echo $TARGET_INDEX_RAW|tr '.' '_') 
-          echo "::set-output name=opp_uncomplete_operators::${{ github.event.inputs.list_of_operators }}"
-          echo "::set-output name=opp_uncomplete_operators_$TARGET_INDEX_UNDERLINE::${{ github.event.inputs.list_of_operators }}"
+          for index in $(echo '${{ github.event.inputs.index }}' | jq -r .[]); do
+              TARGET_INDEX_RAW=$(echo $index|cut -d '-' -f1)
+              TARGET_INDEX_UNDERLINE=$(echo $TARGET_INDEX_RAW|tr '.' '_')
+              export OPP_FORCE_OPERATORS_$TARGET_INDEX_UNDERLINE="${{ github.event.inputs.list_of_operators }}"
+              echo "opp_uncomplete_operators_$TARGET_INDEX_UNDERLINE=${{ github.event.inputs.list_of_operators }}" >> $GITHUB_OUTPUT
+          done
+          echo "opp_uncomplete_operators=${{ github.event.inputs.list_of_operators }}" >> $GITHUB_OUTPUT
 
       - name: Index check
         run: |
@@ -216,6 +236,8 @@ jobs:
         env:
 
           OPP_FORCE_OPERATORS: "${{ github.event.inputs.list_of_operators }}"
+          OPP_OP_INFO_PARALLEL: 1
+          OPP_OP_INFO_PARALLEL_BATCH: 20
 
           OPP_AUTO_LABEL: 1
           ANSIBLE_FORCE_COLOR: 1
@@ -225,7 +247,12 @@ jobs:
           OPP_FORCE_OPERATORS=${OPP_FORCE_OPERATORS// /,}
           echo $OPP_FORCE_OPERATORS
           [ "$OPP_AUTO_LABEL" = '1' ] && ANSIBLE_ARGS="-e automatic_cluster_version_label=true" || ANSIBLE_ARGS="-e automatic_cluster_version_label=false"
-          ansible-pull -U $OPP_ANSIBLE_PULL_REPO -C $OPP_ANSIBLE_PULL_BRANCH -i localhost, -e run_upstream=true -e run_prepare_catalog_repo_upstream=true -e catalog_repo=$OPP_THIS_REPO_BASE/$OPP_THIS_REPO -e catalog_repo_branch=$OPP_THIS_BRANCH upstream/local.yml --tags reset_tools,operator_info -e operator_base_dir=/tmp/community-operators-for-catalog/operators -e operators=$OPP_FORCE_OPERATORS -e cluster_type=$OPP_PRODUCTION_TYPE -e strict_cluster_version_labels=true -e stream_kind=openshift_upstream -e production_registry_namespace=$OPP_RELEASE_BUNDLE_REGISTRY/$OPP_RELEASE_BUNDLE_ORGANIZATION $ANSIBLE_ARGS
+          [ "$OPP_OP_INFO_PARALLEL" = '1' ] && ANSIBLE_ARGS="$ANSIBLE_ARGS -e op_info_parallel=true -e op_info_parallel_batch=$OPP_OP_INFO_PARALLEL_BATCH" || ANSIBLE_ARGS="$ANSIBLE_ARGS -e op_info_parallel=false"
+          echo $ANSIBLE_ARGS
+          git clone $OPP_ANSIBLE_PULL_REPO -b $OPP_ANSIBLE_PULL_BRANCH operator-test-playbooks
+          cd operator-test-playbooks
+          ansible-playbook -i localhost, -e ansible_connection=local -e run_upstream=true -e run_prepare_catalog_repo_upstream=true -e catalog_repo=$OPP_THIS_REPO_BASE/$OPP_THIS_REPO -e catalog_repo_branch=$OPP_THIS_BRANCH upstream/local.yml --tags reset_tools,operator_info -e operator_base_dir=/tmp/community-operators-for-catalog/operators -e operators=$OPP_FORCE_OPERATORS -e cluster_type=$OPP_PRODUCTION_TYPE -e strict_cluster_version_labels=true -e stream_kind=openshift_upstream -e production_registry_namespace=$OPP_RELEASE_BUNDLE_REGISTRY/$OPP_RELEASE_BUNDLE_ORGANIZATION $ANSIBLE_ARGS
+
       - name: Upload operator_info
         uses: actions/upload-artifact@v2
         with:
@@ -238,7 +265,7 @@ jobs:
           path: "/tmp/operator-test/operators"
       - shell: bash
         run: |
-          [ -f /tmp/operator-test/op_info.yaml ] && cat /tmp/operator-test/op_info.yaml || echo "::set-output name=opp_uncomplete_operators::"          
+          [ -f /tmp/operator-test/op_info.yaml ] && cat /tmp/operator-test/op_info.yaml || echo "opp_uncomplete_operators=" >> $GITHUB_OUTPUT    
     outputs:
       opp_uncomplete_operators: "${{ steps.operators.outputs.opp_uncomplete_operators }}"
       opp_uncomplete_operators_v4_6: "${{ steps.operators.outputs.opp_uncomplete_operators_v4_6 }}"
@@ -273,6 +300,7 @@ jobs:
           IIB_INPUT_REGISTRY_TOKEN: ${{ secrets.IIB_INPUT_REGISTRY_TOKEN }}
           OPERATOR_INDEX_TAG: latest
           OPP_SKIP_INDEX: 1
+          OPP_SKIP_BUNDLES: 0
           OPP_FORCE_OPERATORS: "${{ needs.operators-ocp.outputs.opp_uncomplete_operators }}"
 
         run: |
@@ -280,7 +308,7 @@ jobs:
           echo "OPP_FORCE_OPERATORS=$OPP_FORCE_OPERATORS"
           FAKE_RC=false
           FAKE_TYPE=$(echo $OPERATOR_INDEX_TAG | cut -d '-' -f 2)
-          [[ $FAKE_TYPE == *rc* ]] && FAKE_RC=true || true
+
           echo "orange_${OPERATOR_INDEX_TAG} operators/sync $OPP_THIS_REPO $OPP_THIS_BRANCH"
           bash <(curl -sL $OPP_SCRIPT_URL) orange_${OPERATOR_INDEX_TAG} operators/sync $OPP_THIS_REPO $OPP_THIS_BRANCH || $FAKE_RC
 
@@ -293,7 +321,7 @@ jobs:
     strategy:
       matrix:
 
-        index-tag: ['${{ github.event.inputs.index }}']
+        index-tag: ${{ fromJson(github.event.inputs.index) }}
 
       fail-fast: false
     steps:
@@ -307,6 +335,12 @@ jobs:
         with:
           name: operators_converted
           path: /tmp/operator-test/operators
+      - name: Print space info (before)
+        run: |
+          du -h -d 3 /tmp | sort  -h -r
+          df -h
+          docker images
+
       - name: Index sync
         env:
           OPP_LABELS: "${{ needs.pr-check.outputs.opp_labels }}"
@@ -316,6 +350,7 @@ jobs:
           OPP_MIRROR_INDEX_ENABLED: ${{ github.event.inputs.mirror_index_to_final_location }}
 
           OPP_FORCE_INDEX_UPDATE: 1
+          OPP_SKIP_BUNDLES: 1
           IIB_INPUT_REGISTRY_TOKEN: ${{ secrets.IIB_INPUT_REGISTRY_TOKEN }}
           IIB_OUTPUT_REGISTRY_TOKEN: ${{ secrets.IIB_OUTPUT_REGISTRY_TOKEN }}
           OPERATOR_INDEX_TAG: ${{ matrix.index-tag }}
@@ -326,84 +361,64 @@ jobs:
           echo "OPP_LABELS=$OPP_LABELS"
           FAKE_RC=false
           FAKE_TYPE=$(echo $OPERATOR_INDEX_TAG | cut -d '-' -f 2)
-          [[ $FAKE_TYPE == *rc* ]] && FAKE_RC=true || true
 
-          TARGET_INDEX_RAW=${{ github.event.inputs.index }}
-          TARGET_INDEX_RAW=$(echo $TARGET_INDEX_RAW|cut -d '-' -f1)
-          TARGET_INDEX_UNDERLINE=$(echo $TARGET_INDEX_RAW|tr '.' '_') 
-          export OPP_FORCE_OPERATORS_$TARGET_INDEX_UNDERLINE="${{ github.event.inputs.list_of_operators }}"
+
+          for index in $(echo '${{ github.event.inputs.index }}' | jq -r .[]); do
+              TARGET_INDEX_RAW=$(echo $index|cut -d '-' -f1)
+              TARGET_INDEX_UNDERLINE=$(echo $TARGET_INDEX_RAW|tr '.' '_')
+              export OPP_FORCE_OPERATORS_$TARGET_INDEX_UNDERLINE="${{ github.event.inputs.list_of_operators }}"
+          done
 
           echo "orange_${OPERATOR_INDEX_TAG} operators/sync $OPP_THIS_REPO $OPP_THIS_BRANCH"
           bash <(curl -sL $OPP_SCRIPT_URL) orange_${OPERATOR_INDEX_TAG} operators/sync $OPP_THIS_REPO $OPP_THIS_BRANCH || $FAKE_RC
-
-  push-to-quay-ocp:
-    name: "Push to quay / ocp"
-
-    needs: pr-check
-    if: needs.pr-check.outputs.opp_release_ready == '1' && needs.pr-check.outputs.opp_name != '' && needs.pr-check.outputs.opp_version != ''
-    runs-on: ubuntu-latest
-    env:
-      DELETE_APPREG: "${{ needs.pr-check.outputs.opp_release_delete_appreg }}"
-      OPP_VERSION: "${{ needs.pr-check.outputs.opp_version }}"
-    steps:
-      - name: Push to quay
+      - name: Print space info (after)
+        if: always()
         run: |
-          echo "push_to_quay operators/${{ needs.pr-check.outputs.opp_name }}/${{ needs.pr-check.outputs.opp_version }} $OPP_THIS_REPO $OPP_THIS_BRANCH"
-          bash <(curl -sL $OPP_SCRIPT_URL) push_to_quay operators/${{ needs.pr-check.outputs.opp_name }}/${{ needs.pr-check.outputs.opp_version }} $OPP_THIS_REPO $OPP_THIS_BRANCH || true
-
-#   release-sha-ocp:
-#     name: "Index production / ocp"
-#     needs: [ pr-check, release-ocp ]
-# 
-#     if: needs.pr-check.outputs.opp_release_ready == '1' && ( github.event.inputs.mirror_index_to_final_location == '' || github.event.inputs.mirror_index_to_final_location != '0')
-#     runs-on: ubuntu-latest
-#     strategy:
-#       matrix:
-# # # # 
-#         index-tag: ['${{ github.event.inputs.index }}']
-# # # 
-#       fail-fast: false
-#     steps:
-      # - name: Download operator_info
-      #   uses: actions/download-artifact@v2
-      #   with:
-      #     name: operator_info
-      #     path: /tmp/operator-test/
-      # - name: Download converted operators
-      #   uses: actions/download-artifact@v2
-      #   with:
-      #     name: operators_converted
-      #     path: /tmp/operator-test/operators
-
-      # - name: Release final index
-      #   env:
-      #     OPERATOR_INDEX_TAG: ${{ matrix.index-tag }}
-      #     IIB_INPUT_REGISTRY_TOKEN: ${{ secrets.IIB_INPUT_REGISTRY_TOKEN }}
-      #     IIB_OUTPUT_REGISTRY_TOKEN: ${{ secrets.IIB_OUTPUT_REGISTRY_TOKEN }}
-      #   run: |
-      #     FAKE_RC=false
-      #     FAKE_TYPE=$(echo $OPERATOR_INDEX_TAG | cut -d '-' -f 2)
-      #     [[ $FAKE_TYPE == *rc* ]] && FAKE_RC=true || true
-
-      #     echo "openshift: $OPERATOR_INDEX_TAG"
-      #     bash <(curl -sL $OPP_SCRIPT_ISS_URL) openshift $OPERATOR_INDEX_TAG || $FAKE_RC
-# 
+          docker exec -t op-test /bin/bash -c "du -h -d 3 /tmp | sort  -h -r" || true
+          docker exec -t op-test /bin/bash -c "podman images ; df -h" || true
+          echo "local df:"
+          df -h
 
   slack-notification:
-    name: "Slack notification"
-    needs: [ pr-check, remove-ocp, operators-ocp, bundles-ocp, release-ocp, push-to-quay-ocp ]
+    name: "Monitoring notification"
+    needs: [ pr-check, remove-ocp, operators-ocp, bundles-ocp, release-ocp , index-verify-ocp ]
 
     if: failure()
     runs-on: ubuntu-latest
     steps:
-      - name: Report Status
-        uses: ravsamhq/notify-slack-action@master
-        with:
-          notification_title: 'Release pipeline failed: ${{ needs.pr-check.outputs.opp_pr_title }}'
-          footer: 'monitoring'
-#          status: ${{ needs.pr-check.result }}
-          status: 'failure'
-          notify_when: 'failure'
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
-        continue-on-error: true
+      - name: Google Chat Notification
+        run: |
+          echo "title: Release pipeline failed: ${{ needs.pr-check.outputs.opp_pr_title }}"
+          echo "subtitle: failure"
+          curl --location --request POST '${{ secrets.GCHAT_WEBHOOK }}' \
+          --header 'Content-Type: application/json' \
+          --data-raw '{
+              "cards": [
+                  {
+                      "header": {
+                          "title": "Release pipeline failed: ${{ needs.pr-check.outputs.opp_pr_title }}",
+                          "subtitle": "failure"
+                      },
+                      "sections": [
+                          {
+                              "widgets": [
+                                  {
+                                      "buttons": [
+                                          {
+                                              "textButton": {
+                                                  "text": "Open the release queue",
+                                                  "onClick": {
+                                                      "openLink": {
+                                                          "url": "https://github.com/${{ github.repository }}/actions/workflows/operator_release.yaml"
+                                                      }
+                                                  }
+                                              }
+                                          }
+                                      ]
+                                  }
+                              ]
+                          }
+                      ]
+                  }
+              ]
+          }'
